### ISSUE TITLE
Unhandled exception in circuit

### ISSUE THREAD

**Issue by mehmet-erdogdu** [VahidN/DNTCaptcha.Blazor#6]
.net 7

fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'nMFpvZLVu6xZ3vsr7injPgCRhmsI6z5nE32LmLjn7Bs'.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.JSInterop.Implementation.JSObjectReference.DisposeAsync()
         at DNTCaptcha.Blazor.DntInputCaptcha.DisposeAsync() in F:\Prog\1400\DNTCaptcha.Blazor\src\DNTCaptcha.Blazor\Components\DntInputCaptcha.razor.cs:line 237
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()

**Comment by VahidN** [comment]
I can't reproduce it. [This Blazor WASM sample](https://vahidn.github.io/DNTCaptcha.Blazor/) and its last nuget version supports .NET 7. Also its [Blazor server sample](https://github.com/VahidN/DNTCaptcha.Blazor/tree/main/src/DNTCaptcha.Blazor.ServerSample) works fine.
